In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
movie_data = pd.read_csv("archive/IMDb_Movies_India.csv", encoding='ISO-8859-1')

In [3]:
movie_data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,(1988),NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,(1999),129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15506,Zulmi Raj,(2005),NaN,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN
15507,Zulmi Shikari,(1988),NaN,Action,NaN,NaN,NaN,NaN,NaN,NaN
15508,Zulm-O-Sitam,(1998),130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [4]:
movie_data.isnull().sum()

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [5]:
movie_data = movie_data.dropna()

In [6]:
movie_data

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,(1997),147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,(2005),142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,(2012),82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia
...,...,...,...,...,...,...,...,...,...,...
15493,Zubaan,(2015),115 min,Drama,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana
15494,Zubeidaa,(2001),153 min,"Biography, Drama, History",6.2,"1,496",Shyam Benegal,Karisma Kapoor,Rekha,Manoj Bajpayee
15503,Zulm Ki Zanjeer,(1989),125 min,"Action, Crime, Drama",5.8,44,S.P. Muthuraman,Chiranjeevi,Jayamalini,Rajinikanth
15505,Zulmi,(1999),129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15508,Zulm-O-Sitam,(1998),130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [7]:
movie_data.isnull().sum()

Name        0
Year        0
Duration    0
Genre       0
Rating      0
Votes       0
Director    0
Actor 1     0
Actor 2     0
Actor 3     0
dtype: int64

In [8]:
duplicate = movie_data[movie_data.duplicated(subset = ['Name', 'Year'], keep = False)]
print("Below are the duplicate rows according to Name and Year:")
duplicate.head()

Below are the duplicate rows according to Name and Year:

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
6062,India's Daughter,(2015),63 min,"Documentary, Biography, Crime",8.2,"1,998",Leslee Udwin,Asha Devi,Badri Singh,Satendra
6063,India's Daughter,(2015),120 min,"Action, Crime, Drama",6.9,21,Rupesh Paul,Omkar Das Manikpuri,Amann Grewal,Vishal Om Prakash
12420,Sant Dnyaneshwar,(1940),139 min,Fantasy,7.9,45,Vishnupant Govind Damle,Sheikh Fattelal,Shahu Modak,Datta Dharmadhikari
12421,Sant Dnyaneshwar,(1940),137 min,Biography,8.1,9,Vishnupant Govind Damle,Sheikh Fattelal,Shahu Modak,Datta Dharmadhikari

In [9]:
movie_data = movie_data.drop_duplicates(subset=['Name', 'Year'])

In [10]:
duplicate = movie_data[movie_data.duplicated(subset = ['Name', 'Year'], keep = False)]
print("Below are the duplicate rows according to Name and Year:")
duplicate.head()

Below are the duplicate rows according to Name and Year:

Empty DataFrame
Columns: [Name, Year, Duration, Genre, Rating, Votes, Director, Actor 1, Actor 2, Actor 3]
Index: []

In [11]:
movie_data.loc[:, 'Year'] = movie_data['Year'].str.replace(r'[()]', '', regex=True).astype(int)
movie_data.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),2019,109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,2019,110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,1997,147 min,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,2005,142 min,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,2012,82 min,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia

In [12]:
movie_data.loc[:, 'Duration'] = movie_data['Duration'].str.replace(r' min', '', regex=True).astype(int)
movie_data.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),2019,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,2019,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,2005,142,"Drama, Romance, War",7.4,"1,086",Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia

In [13]:
movie_data.loc[:, 'Votes'] = movie_data['Votes'].str.replace(r',', '', regex=True).astype(int)
movie_data.head()

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
1,#Gadhvi (He thought he was Gandhi),2019,109,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
3,#Yaaram,2019,110,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
5,...Aur Pyaar Ho Gaya,1997,147,"Comedy, Drama, Musical",4.7,827,Rahul Rawail,Bobby Deol,Aishwarya Rai Bachchan,Shammi Kapoor
6,...Yahaan,2005,142,"Drama, Romance, War",7.4,1086,Shoojit Sircar,Jimmy Sheirgill,Minissha Lamba,Yashpal Sharma
8,?: A Question Mark,2012,82,"Horror, Mystery, Thriller",5.6,326,Allyson Patel,Yash Dave,Muntazir Ahmad,Kiran Bhatia

In [14]:
movie_data.dtypes

Name         object
Year         object
Duration     object
Genre        object
Rating      float64
Votes        object
Director     object
Actor 1      object
Actor 2      object
Actor 3      object
dtype: object

In [15]:
movie_data_copy = movie_data.copy()
movie_data_copy['Year'] = pd.to_numeric(movie_data_copy['Year'], errors='coerce', downcast='integer').astype('Int64')
movie_data_copy['Duration'] = pd.to_numeric(movie_data_copy['Duration'], errors='coerce', downcast='integer').astype('Int64')
movie_data_copy['Votes'] = pd.to_numeric(movie_data_copy['Votes'], errors='coerce', downcast='integer').astype('Int64')
movie_data = movie_data_copy

In [16]:
movie_data.dtypes

Name         object
Year          Int64
Duration      Int64
Genre        object
Rating      float64
Votes         Int64
Director     object
Actor 1      object
Actor 2      object
Actor 3      object
dtype: object

In [17]:
# Step 1: Split the genres into lists
movie_data['Genre'] = movie_data['Genre'].apply(lambda x: x.split(', '))

# Step 2: Perform one-hot encoding
movie_data = movie_data.explode('Genre')  # Create a row for each genre per movie
movie_data = pd.get_dummies(movie_data, columns=['Genre'])

# Step 3: Aggregate back to the original format
movie_data = movie_data.groupby('Name').sum().reset_index()

movie_data

,Name,Year,Duration,Rating,Votes,Director,Actor 1,Actor 2,Actor 3,Genre_Action,...,Genre_Music,Genre_Musical,Genre_Mystery,Genre_News,Genre_Romance,Genre_Sci-Fi,Genre_Sport,Genre_Thriller,Genre_War,Genre_Western
0,#Gadhvi (He thought he was Gandhi),2019,109,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid,0,...,0,0,0,0,0,0,0,0,0,0
1,#Yaaram,4038,220,8.8,70,Ovais KhanOvais Khan,PrateikPrateik,Ishita RajIshita Raj,Siddhant KapoorSiddhant Kapoor,0,...,0,0,0,0,1,0,0,0,0,0
2,'Ferry',3908,256,11.6,56,Hemen GuptaHemen Gupta,Dev AnandDev Anand,ArchanaArchana,BabuBabu,0,...,0,0,0,0,0,0,0,0,0,0
3,...Aur Pyaar Ho Gaya,5991,441,14.1,2481,Rahul RawailRahul RawailRahul Rawail,Bobby DeolBobby DeolBobby Deol,Aishwarya Rai BachchanAishwarya Rai BachchanAi...,Shammi KapoorShammi KapoorShammi Kapoor,0,...,0,1,0,0,0,0,0,0,0,0
4,...Yahaan,6015,426,22.2,3258,Shoojit SircarShoojit SircarShoojit Sircar,Jimmy SheirgillJimmy SheirgillJimmy Sheirgill,Minissha LambaMinissha LambaMinissha Lamba,Yashpal SharmaYashpal SharmaYashpal Sharma,0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5380,Zubaan,2015,115,6.1,408,Mozez Singh,Vicky Kaushal,Sarah Jane Dias,Raaghavv Chanana,0,...,0,0,0,0,0,0,0,0,0,0
5381,Zubeidaa,6003,459,18.6,4488,Shyam BenegalShyam BenegalShyam Benegal,Karisma KapoorKarisma KapoorKarisma Kapoor,RekhaRekhaRekha,Manoj BajpayeeManoj BajpayeeManoj Bajpayee,0,...,0,0,0,0,0,0,0,0,0,0
5382,Zulm Ki Zanjeer,5967,375,17.4,132,S.P. MuthuramanS.P. MuthuramanS.P. Muthuraman,ChiranjeeviChiranjeeviChiranjeevi,JayamaliniJayamaliniJayamalini,RajinikanthRajinikanthRajinikanth,1,...,0,0,0,0,0,0,0,0,0,0
5383,Zulm-O-Sitam,3996,260,12.4,40,K.C. BokadiaK.C. Bokadia,DharmendraDharmendra,Jaya PradaJaya Prada,Arjun SarjaArjun Sarja,1,...,0,0,0,0,0,0,0,0,0,0
5384,Zulmi,3998,258,9.0,1310,Kuku KohliKuku Kohli,Akshay KumarAkshay Kumar,Twinkle KhannaTwinkle Khanna,Aruna IraniAruna Irani,1,...,0,0,0,0,0,0,0,0,0,0

In [18]:
categorical_columns = ['Director', 'Actor 1', 'Actor 2', 'Actor 3']
movie_data = pd.get_dummies(movie_data, columns=categorical_columns)

In [19]:
movie_data

,Name,Year,Duration,Rating,Votes,Genre_Action,Genre_Adventure,Genre_Animation,Genre_Biography,Genre_Comedy,...,Actor 3_Zayed KhanZayed KhanZayed Khan,Actor 3_Zeenat Aman,Actor 3_Zeenat AmanZeenat Aman,Actor 3_Zeenat AmanZeenat AmanZeenat Aman,Actor 3_Zeenat AmanZeenat AmanZeenat AmanPriyanka Chopra JonasPriyanka Chopra JonasPriyanka Chopra Jonas,Actor 3_Zeeshan KhanZeeshan KhanZeeshan Khan,Actor 3_Zeishan QuadriZeishan Quadri,Actor 3_Zenobia ShroffZenobia ShroffZenobia Shroff,Actor 3_Zoya Hussain,Actor 3_Zoya HussainZoya HussainZoya Hussain
0,#Gadhvi (He thought he was Gandhi),2019,109,7.0,8,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
1,#Yaaram,4038,220,8.8,70,0,0,0,0,1,...,False,False,False,False,False,False,False,False,False,False
2,'Ferry',3908,256,11.6,56,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
3,...Aur Pyaar Ho Gaya,5991,441,14.1,2481,0,0,0,0,1,...,False,False,False,False,False,False,False,False,False,False
4,...Yahaan,6015,426,22.2,3258,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5380,Zubaan,2015,115,6.1,408,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
5381,Zubeidaa,6003,459,18.6,4488,0,0,0,1,0,...,False,False,False,False,False,False,False,False,False,False
5382,Zulm Ki Zanjeer,5967,375,17.4,132,1,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
5383,Zulm-O-Sitam,3996,260,12.4,40,1,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
5384,Zulmi,3998,258,9.0,1310,1,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False

In [20]:
movie_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5385 entries, 0 to 5384
Columns: 12880 entries, Name to Actor 3_Zoya HussainZoya HussainZoya Hussain
dtypes: Int64(3), bool(12853), float64(1), int64(22), object(1)
memory usage: 67.1+ MB

In [21]:
movie_data.dtypes

Name                                                   object
Year                                                    Int64
Duration                                                Int64
Rating                                                float64
Votes                                                   Int64
                                                       ...
Actor 3_Zeeshan KhanZeeshan KhanZeeshan Khan             bool
Actor 3_Zeishan QuadriZeishan Quadri                     bool
Actor 3_Zenobia ShroffZenobia ShroffZenobia Shroff       bool
Actor 3_Zoya Hussain                                     bool
Actor 3_Zoya HussainZoya HussainZoya Hussain             bool
Length: 12880, dtype: object

In [22]:
data = movie_data.drop(['Name'], axis = 1, inplace = True)

In [23]:
movie_data

,Year,Duration,Rating,Votes,Genre_Action,Genre_Adventure,Genre_Animation,Genre_Biography,Genre_Comedy,Genre_Crime,...,Actor 3_Zayed KhanZayed KhanZayed Khan,Actor 3_Zeenat Aman,Actor 3_Zeenat AmanZeenat Aman,Actor 3_Zeenat AmanZeenat AmanZeenat Aman,Actor 3_Zeenat AmanZeenat AmanZeenat AmanPriyanka Chopra JonasPriyanka Chopra JonasPriyanka Chopra Jonas,Actor 3_Zeeshan KhanZeeshan KhanZeeshan Khan,Actor 3_Zeishan QuadriZeishan Quadri,Actor 3_Zenobia ShroffZenobia ShroffZenobia Shroff,Actor 3_Zoya Hussain,Actor 3_Zoya HussainZoya HussainZoya Hussain
0,2019,109,7.0,8,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
1,4038,220,8.8,70,0,0,0,0,1,0,...,False,False,False,False,False,False,False,False,False,False
2,3908,256,11.6,56,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
3,5991,441,14.1,2481,0,0,0,0,1,0,...,False,False,False,False,False,False,False,False,False,False
4,6015,426,22.2,3258,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5380,2015,115,6.1,408,0,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
5381,6003,459,18.6,4488,0,0,0,1,0,0,...,False,False,False,False,False,False,False,False,False,False
5382,5967,375,17.4,132,1,0,0,0,0,1,...,False,False,False,False,False,False,False,False,False,False
5383,3996,260,12.4,40,1,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False
5384,3998,258,9.0,1310,1,0,0,0,0,0,...,False,False,False,False,False,False,False,False,False,False

In [24]:
from sklearn.model_selection import train_test_split

x = movie_data.drop(['Rating'], axis = 1)
y = movie_data['Rating']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [25]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 200, 500]  
}

rf = RandomForestRegressor(random_state=42)
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=5, scoring='neg_mean_squared_error', verbose=1, n_jobs=-1)
grid_search.fit(x_train, y_train)

print(f'Best n_estimators: {grid_search.best_params_["n_estimators"]}')

Fitting 5 folds for each of 4 candidates, totalling 20 fits
Best n_estimators: 100

In [26]:
# Get best estimator from grid search
best_rf = grid_search.best_estimator_

In [27]:
# Predict on test data using best estimator
y_pred = best_rf.predict(x_test)

In [29]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, root_mean_squared_error

# Calculate Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)
print(f'Mean Squared Error (MSE): {mse:.2f}')

# Calculate R-squared (Coefficient of Determination)
r2 = r2_score(y_test, y_pred)
print(f'R-squared (R2): {r2:.2f}')

# Calculate Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, y_pred)
print(f'Mean Absolute Error (MAE): {mae:.2f}')

# Calculate Root Mean Squared Error (RMSE)
rmse = root_mean_squared_error(y_test, y_pred)
print(f'Root Mean Squared Error (RMSE): {rmse:.2f}')

Mean Squared Error (MSE): 6.36
R-squared (R2): 0.87
Mean Absolute Error (MAE): 1.76
Root Mean Squared Error (RMSE): 2.52